services:
  - type: web
    name: temawii-makeup-demo
    runtime: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
